services:
  - type: web
    name: ai-resume-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: ml-model
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
